ques 1 What is a parameter?

In machine learning, a parameter refers to the internal variables that a model learns from the data during the training process. These parameters define how the model makes predictions and ultimately control the behavior of the model.

ques 2 What is correlation?
 What does negative correlation mean.

 Correlation refers to a statistical relationship or association between two or more variables. In simple terms, it measures how changes in one variable are related to changes in another.

 A negative correlation means that as one variable increases, the other variable tends to decrease, and vice versa which means there is an inverse relationship between the two variables



ques 3 Define Machine Learning. What are the main components in Machine Learning?

Machine Learning (ML) is a branch of artificial intelligence (AI) that allows computers to learn from and make decisions based on data, without being explicitly programmed.

The core idea of machine learning is to build models from data, allowing the system to learn and make accurate predictions or decisions based on that data.

The main components are:

* Data (input and output)

* Algorithms (methods to learn from data)

* Model (the learned representation)

* Features (input variables)

* Labels (output to predict)

* Training (learning process)

* Evaluation (measuring performance)

* Prediction/Inference (applying the model to new data)

* Optimization (improving the model)

ques 4 How does loss value help in determining whether the model is good or not?

n machine learning, the loss value (or loss function) is a key metric used to evaluate how well a model's predictions match the actual data. It helps determine whether the model is performing well or if adjustments are needed. The lower the loss value, the better the model is at making accurate predictions.

The loss value is an important tool for:

1. Assessing model performance: A lower loss indicates better predictions.

2. Guiding the optimization process: It helps adjust model parameters to minimize error.

3. Detecting overfitting or underfitting: Helps to determine whether the model is generalizing well or not.

4. Comparing models: Helps you choose the best model based on performance

ques 5 What are continuous and categorical variables?

 **Continuous variable**s:  are numerical variables that can take an infinite number of values within a given range. They can represent quantities that can be measured with great precision, and the values can have decimals or fractions.

eg height , weight , temperature etc.

 **Categorical variables**:  are variables that represent categories or groups. These variables describe qualitative attributes or characteristics that can be divided into a finite set of categories or groups.

  eg Gender( Male, Female) , Color (Red, Blue, Green) .



ques 6 How do we handle categorical variables in Machine Learning? What are the common techniques?

In machine learning, categorical variables need to be handled properly because most algorithms work with numerical data, not raw categorical data. Therefore, we must convert categorical variables into numerical formats while retaining the information contained in them. Here are some common techniques to handle categorical variables:

1. Label Encoding:

Label Encoding is a method where each category of a categorical variable is assigned a unique integer value.

2. One-Hot Encoding:

One-hot encoding creates binary columns (0 or 1) for each category in a categorical variable. It transforms a categorical variable into several new binary variables, each representing a single category.

3. Binary Encoding:

Binary encoding is a technique that combines the benefits of label encoding and one-hot encoding. It is used when the categorical variable has a large number of categories (high cardinality).

ques 7 What do you mean by training and testing a dataset?

In machine learning, training and testing a dataset refer to two distinct steps in the model development process. These steps help evaluate how well a machine learning model is performing and ensure that the model generalizes well to unseen data.

**Training a dataset**: The model learns from the data by adjusting its parameters based on the training set.

**Testing a dataset**: The model is evaluated on unseen data (testing set) to assess its performance and generalization ability.


 ques 8 What is sklearn.preprocessing?

 sklearn.preprocessing is a module in scikit-learn that provides various utilities and methods to preprocess data before feeding it into machine learning models. Preprocessing is an important step in the machine learning pipeline, as it transforms raw data into a suitable format that models can understand and learn from effectively.

ques 9 What is a Test set?

A test set is a subset of the dataset that is used to evaluate the performance of a machine learning model after it has been trained. It contains data that the model has not seen during the training process, allowing you to assess how well the model generalizes to new, unseen data.

This helps ensure that the model is not just memorizing the training data (overfitting) but is capable of making accurate predictions on real-world data.

In [4]:
#ques 10  How do we split data for model fitting (training and testing) in Python? How do you approach a Machine Learning problem?
import numpy as np
from sklearn.model_selection import train_test_split
X = np.array([[1,2],[3,4],[5,6],[7,8]])
y = np.array([0,1,0,1])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



Steps to Approach a Machine Learning Problem:

1. Define the problem: Understand the type of problem (classification, regression, etc.).

2. Collect and explore the data: Analyze and visualize the data to understand it.

3. Preprocess the data: Clean and prepare the data (handle missing values, scale features, etc.).

4. Split the data: Split into training and testing sets using train_test_split.

5. Choose a model: Select an appropriate machine learning model.

6. Train the model: Fit the model to the training data.

7. Evaluate the model: Test the model using the test set and evaluate performance.

8. Improve the model: Tune hyperparameters, try different models, or use ensemble methods.

9. Deploy the model: Deploy the trained model for making predictions on new data.





ques 11  Why do we have to perform EDA before fitting a model to the data?

EDA is crucial because it allows you to clean, understand, and preprocess your data before fitting a model. Without EDA, you risk using poorly prepared data, which can lead to suboptimal model performance, incorrect assumptions, and wasted time.

ques 12 What is correlation?

Correlation is a statistical measure that describes the relationship between two variables. It quantifies how strongly two variables are related to each other. When two variables are correlated, a change in one variable tends to result in a predictable change in the other variable.

ques 13 What does negative correlation mean?

A negative correlation means that as one variable increases, the other variable tends to decrease, and vice versa.  there is an inverse relationship between the two variables. When one variable goes up, the other goes down, and when one variable goes down, the other goes up.

In [5]:
#ques 14 How can you find correlation between variables in Python?

import pandas as pd
data = {
    'Hours_Studied': [1, 2, 3, 4, 5, 6, 7, 8],
    'Test_Score': [45, 50, 55, 60, 65, 70, 75, 80]
}
df = pd.DataFrame(data)
correlation = df['Hours_Studied'].corr(df['Test_Score'])
print(f'Correlation between Hours_Studied and Test_Score: {correlation}')


Correlation between Hours_Studied and Test_Score: 1.0


ques 15 What is causation? Explain difference between correlation and causation with an example.

Causation refers to a relationship between two variables where one variable directly influences the other.

**Correlation:**Indicates that two variables are related in some way but does not imply that one causes the other. For example, ice cream sales and drowning deaths are correlated but do not have a direct causal relationship.

**Causation:** Implies that one variable directly influences the other. For example, education levels can cause higher income levels, as education provides skills and qualifications that lead to better job opportunities.

ques 16  What is an Optimizer? What are different types of optimizers? Explain each with an example

An optimizer in machine learning is a method used to minimize (or maximize) a loss function by adjusting the parameters of the model during the training process.

type of optimizers:

Gradient Descent (GD): Basic, full dataset.

Stochastic Gradient Descent (SGD): Updates based on a single example.

Mini-Batch GD: Uses small batches.

Momentum: Accelerates convergence by using past gradients.

ques 17  What is sklearn.linear_model ?

**sklearn.linear_model** is a module in the scikit-learn library that provides several classes and functions to perform linear modeling techniques, primarily used for regression and classification tasks.



ques 18 What does model.fit() do? What arguments must be given?

model.fit() trains the model using the input features (X) and the target labels (y).

Syntax:

model.fit(X, y)

The required arguments are:

X: Input feature matrix (2D array-like).

y: Target vector (1D array-like).

ques 19 What does model.predict() do? What arguments must be given?

model.predict() is used to make predictions on new data after training a model with model.fit().

The required argument is:

X: Input features for which you want to predict the target values or class labels.

Syntax:

predictions = model.predict(X)

ques 20 What are continuous and categorical variables?

 * Continuous Variables:

Continuous variables are numeric variables that can take any value within a range. These values can be integers or decimals and can represent quantities that can be measured on a scale.

* Categorical Variables:

Categorical variables are non-numeric variables that represent categories or groups. These variables have a limited number of distinct values (called categories or labels).

ques 21 What is feature scaling? How does it help in Machine Learning?

Feature scaling refers to the process of scaling the range of features to a standard or normalized range, ensuring that each feature contributes equally to the model’s performance.

It is essential for algorithms that depend on distance calculations, gradient descent optimization, or regularization.

In [7]:
# ques 22  How do we perform scaling in Python?

from sklearn.preprocessing import StandardScaler
import numpy as np
X = np.array([[1, 200], [2, 300], [3, 400], [4, 500]])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Standardized Data (Z-Score Normalization):\n", X_scaled)


Standardized Data (Z-Score Normalization):
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


ques 23 What is sklearn.preprocessing?

sklearn.preprocessing is a powerful module in scikit-learn that offers a wide range of preprocessing techniques to handle various data types and requirements. Properly preprocessing data is a crucial step in ensuring machine learning models perform well and produce accurate predictions.


In [9]:
#ques 24  How do we split data for model fitting (training and testing) in Python?

from sklearn.model_selection import train_test_split
import numpy as np
X = np.array([[1, 2], [3, 4], [5, 6],])
y = np.array([0, 1, 0,])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("X_train:\n", X_train)
print("X_test:\n", X_test)
print("y_train:", y_train)
print("y_test:", y_test)


X_train:
 [[3 4]
 [5 6]]
X_test:
 [[1 2]]
y_train: [1 0]
y_test: [0]


ques 25 Explain data encoding?

Data encoding is the process of converting categorical or non-numeric data into a numeric format so that it can be used in machine learning models, which typically require numeric input for training. Since most machine learning algorithms cannot directly handle categorical data (like strings or labels), encoding transforms the categorical data into a suitable numerical form